### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by Isaksson** [bhuebschen/dreame-mower#4]
Hello.
I understand that most of the Dreame a1 is stored now during winter, at least in the northern part.
In Sweden there is a great deal for this device now during Black Friday (Black week (Black month)) so I will get one and start using it in the spring.
But my question is if you still plan to continue this project?

**Comment by bhuebschen** [comment]
Yes, the project is still active... even though I don't invest much time in it at the moment

**Comment by Isaksson** [comment]
> Yes, the project is still active... even though I don't invest much time in it at the moment

That was exactly what I wanted to hear, then I do not have to look any further.
It would be nice to integrate the Dreame a1 to HA.

I am also maintaining some public repos and I know the feeling, its hard to invest the time, but from time to time the motivation goes up and a lot of work is done :)

Thanks for the reply.
